### PR TITLE
Fix GH-38

### LINKED ISSUE #38: Oddities when mixing TypeGuards with PartialTypeGuards
The following appears to compile and run and hence do the wrong thing.

```
const isFoo: tg.PartialTypeGuard<string, "foo"> = (s: string): s is "foo" => s === "foo";
const isSomething: { foo: "foo"[] } = tg.isRecord("foo", tg.narrowArray(isFoo));
```

### PR DESCRIPTION
**Pull request by mscharley**
Closes #38

### CODE REVIEW

**Comment by mscharley** [comment]
@jamesharv I'd appreciate your insight and feedback here if you have some time.

File: src/guards.ts [hunk 1]
```diff
@@ -1,3 +1,7 @@
 
+// tslint:disable-next-line:ban-types
+export type NotEmpty = {} | object | number | string | boolean | symbol | Function;
```
Comment (mscharley) [inline src/guards.ts]: Symbols. Don’t forget symbols
